[[redirects]]
  from = "https://dermascan.me/*"
  to = "https://www.dermascan.me/:splat"
  status = 301
  force = true

  [[redirects]]
  from = "http://dermascan.me/*"
  to = "https://www.dermascan.me/:splat"
  status = 301
  force = true